[package]
name = "auth"
version = "1.0.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
mongodb = "3"
env_logger = "0.11"
log = "0.4"
uuid = { version = "1", features = ["v4"] }
