apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    {{- include "auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.rootUser | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.rootPassword | quote }}
  MONGO_URI: "mongodb://{{ .Values.mongodb.rootUser }}:{{ .Values.mongodb.rootPassword }}@mongodb-0.mongodb.{{ .Release.Namespace }}.svc.cluster.local:27017/{{ .Values.mongodb.database }}?authSource=admin"
