apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    {{- include "auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: mongodb
  ports:
    - port: 27017
      targetPort: mongodb
      name: mongodb
