apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    {{- include "auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  selector:
    app.kubernetes.io/component: auth
  ports:
    - port: 8080
      targetPort: http
      name: http
