apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: postgresql
  ports:
    - port: 5432
      targetPort: postgresql
      name: postgresql
