replicaCount: 2

image:
  repository: andygolubev/eks-demo-backend
  tag: "sha-75ce8bb"
  pullPolicy: IfNotPresent

service:
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

postgresql:
  replicas: 1
  image:
    repository: postgres
    tag: "16-alpine"
  storage:
    size: 5Gi
    storageClass: gp2
  database: appdb
  user: appuser
  password: apppass

migrations:
  image:
    repository: andygolubev/eks-demo-migrations
    tag: "sha-75ce8bb"
    pullPolicy: IfNotPresent
